---
ListingsPage:
  extensions:
    - ExcludeChildren
SiteConfig:
  extensions:
    - RealEstateSiteConfig
File:
  extensions:
    - RMSImageExtension
    - RMSFileExtension
Listing:
  extensions:
    - 'Gallery_PageExtension'
    - 'CatalogPageExtension'
  parentClass:
    - 'ListingsPage'

ListingUtils:
  InlcudeMLS: 0


LeftAndMain:
  menu_groups:
    Content:
      - HomePageAdmin
      - AboutUsAdmin
      - ContactUsAdmin
      - CMSPagesController
      - AssetAdmin