---
ListingsPage:
  extensions:
    - ExcludeChildren
SiteConfig:
  extensions:
    - RealEstateSiteConfig
File:
  extensions:
    - RMSImageExtension
    - RMSFileExtension
Page:
  extensions:
    - 'Gallery_PageExtension'